#ifndef OPCODE_H
#define OPCODE_H

enum OpCode {
  OPCODE_CONSTANT,      // 8 bits
  OPCODE_CONSTANT_LONG, // 24 bits
  OPCODE_NIL,
  OPCODE_TRUE,
  OPCODE_FALSE,
  OPCODE_BANG_EQUAL,
  OPCODE_EQUAL_EQUAL,
  OPCODE_GREATER,
  OPCODE_GREATER_EQUAL,
  OPCODE_LESS,
  OPCODE_LESS_EQUAL,
  OPCODE_ADD,
  OPCODE_SUBTRACT,
  OPCODE_MULTIPLY,
  OPCODE_DIVIDE,
  OPCODE_NOT,
  OPCODE_NEGATE,
  OPCODE_RETURN,
};

#endif // OPCODE_H